esphome:
  name: gesture-sensor-1
  friendly_name: Gesture Sensor 1

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "jxIaGryJgNSyfJ5KQ40QKAUF16KLzWMQMUXH+v027wc="

ota:
  - platform: esphome
    password: "adf043dc1df0bf2c120f1bfe205dc854"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gesture-Sensor-1"
    password: "9lnauSoOvhh4"

captive_portal:

# --- NEW PAJ7660 CONFIGURATION BELOW ---

# Pulls in your custom C++ wrapper from GitHub
external_components:
  - source: github://tytremblay/paj7660-esphome
    # Note: If you want to test your code locally before pushing to GitHub, 
    # comment out the line above and uncomment the line below:
    # - source: components

# Configures the hardware I2C pins for the XIAO ESP32-C6
i2c:
  id: bus_a
  sda: GPIO22
  scl: GPIO23
  scan: true

# Exposes the gestures to Home Assistant
text_sensor:
  - platform: pag7660
    name: "Kitchen Lighting Gestures"
    i2c_id: bus_a